version: "3"

services:
  postgres:
    image: postgres:12.4-alpine
    container_name: postgres_dev
    environment:
      POSTGRES_DB: batcoms
      POSTGRES_PASSWORD: password # Or use a .env file for real passwords
    ports:
      - 14000:5432
    volumes:
      - postgresql:/var/lib/postgresql
    restart: unless-stopped

  api:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile.dev
    container_name: api_dev
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PASSWORD: password # Or use a .env file for real passwords
    ports:
      - 3000:3000
    depends_on:
      - postgres
    volumes:
      - ..:/go/src/github.com/sasalatart/batcoms/
    restart: unless-stopped
    command: air -c docker/.air.toml

volumes:
  postgresql:
