PORT: 3000
PORT_TEST: 8888
PSQL_HOST: localhost
PSQL_PORT: 5432
PSQL_USER: postgres
PSQL_NAME: batcoms
PSQL_NAME_TEST: batcoms_test
PSQL_PASS: password
SCRAPER_RESULTS:
  ACTORS: actors.json
  BATTLES: battles.json
TEST_SEEDERS:
  ACTORS: seeders/actors.json
  BATTLES: seeders/battles.json
