PORT: 3000
PORT_TEST: 8888
POSTGRES_HOST: localhost
POSTGRES_PORT: 5432
POSTGRES_USER: postgres
POSTGRES_DB: batcoms
POSTGRES_DB_TEST: batcoms_test
POSTGRES_PASS: password
SCRAPER_RESULTS:
  ACTORS: actors.json
  BATTLES: battles.json
TEST_SEEDERS:
  ACTORS: seeders/actors.json
  BATTLES: seeders/battles.json
